### ISSUE TITLE
Differences between M3 BottomSheet and ModalSheet

### ISSUE THREAD

**Issue by shakil807g** [oleksandrbalan/modalsheet#24]
I really love this library, and I haven't faced any problems while using it. I am just wondering if there would be any additional benefits in using the M3 bottomSheet.

**Comment by oleksandrbalan** [comment]
Thx for using ModalSheet 🤗 

IMHO:
1. M3 [ModalBottomSheet](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/ModalBottomSheet.kt) is an official solution and implementation, but as for now (early 2023) it is a little bit buggy, see issues in the [issue tracker](https://issuetracker.google.com/issues?q=status:open%20componentid:742043%20ModalBottomSheet) related to modal bottom sheet. When most issues will be resolved I think we all could migrate and use an official component.
2. Also as for now there is no official M2 modal bottom sheet implementation with the same API as M3. There is only a [ModalBottomSheetLayout](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/ModalBottomSheet.kt) implementation, which is hard to use for example in destinations with the bottom navigation bar. I believe that M3 implementation will be back-ported to M2 in some future, but I am not aware when and if ever.
3. However this library offers something "on top". I mean it's ["data" overload](https://github.com/oleksandrbalan/modalsheet#alternative-overloads), which could be used when modal sheet content is dynamic and it guarantees correct exit animation when data is set to null.

**Comment by yoongtran** [comment]
My reason for switching to using the ModalSheet is to address an issue that I am getting when using the M3 ModalBottomSheet. The issue with the ModalBottomSheet is when a Dropdown Menu is shown while the modal bottom sheet is visible, the menu would be shown behind the bottom sheet. This library fixes that issue, but  I notice 2 issues when using this library on my project that is on M3. 

Issues:
1. Including the navigationBarsPadding to ModalSheet's modifier is not respected. It would behave like a bottom padding and adds padding above the navigation bar view instead of adjusting the view in relations to the bar.
2. Standard M3 ModalBottomhSheet when shown will maintain the default color of the navigation bar, which is black. However when I switch over to using  the ModalSheet and when shown, the navigation bar is white. 

Thanks

**Comment by oleksandrbalan** [comment]
I guess the dropdown menu (which is essentially a popup) is fixed because we are using the custom implementation of the Popup (`FullscreenPopup`), which fixes some other popup related stuff. I have created an [issue](https://issuetracker.google.com/issues/216662636) about a crash we have in `Popup` more than a year ago 🙈 

As to your issues, may I ask you to [create](https://github.com/oleksandrbalan/modalsheet/issues/new) 2 new issues and attach some video and / or screenshots to them? If you add some small reproduction examples it will greatly help.

Thanks in advance.
