### ISSUE TITLE
Can FullscreenPopup be replaced with Popup()

### ISSUE THREAD

**Issue by LZRight123** [oleksandrbalan/modalsheet#34]
Can FullscreenPopup be replaced with Popup()？

**Comment by oleksandrbalan** [comment]
In theory it could work, see https://github.com/oleksandrbalan/modalsheet/issues/30#issuecomment-1579173167 👀 

But I remember that there was an issue with copy-paste menu for TextField in Popup, I have filed an issue a long time ago: https://issuetracker.google.com/issues/216662636.

Maybe it is already fixed in newer versions of Compose 🤷 
But yea, it is worth to try to replace custom popup implementation with official `Popup` one.
